<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Digital Wallet</label>
    <navType>Standard</navType>
    <tabs>standard-ConsumptionCards</tabs>
    <tabs>standard-ConsumptionTags</tabs>
    <tabs>standard-ConsumptionAnalytics</tabs>
    <tabs>standard-LicenseUtilization</tabs>
    <tabs>childd1__c</tabs>
    <tabs>manPar1__c</tabs>
    <tabs>manPar10__c</tabs>
    <tabs>manPar11__c</tabs>
    <tabs>manPar12__c</tabs>
    <tabs>vaultA__c</tabs>
    <tabs>vaultB__c</tabs>
    <tabs>vaultC__c</tabs>
    <tabs>vaultD__c</tabs>
    <tabs>vaultE__c</tabs>
    <tabs>vaultF__c</tabs>
    <tabs>vaultG__c</tabs>
    <tabs>vaultH__c</tabs>
    <tabs>vaultJ__c</tabs>
    <tabs>vaultK__c</tabs>
    <tabs>vaultL__c</tabs>
    <tabs>vaultM__c</tabs>
    <tabs>vaultN__c</tabs>
    <tabs>vaultO__c</tabs>
    <tabs>vaultP__c</tabs>
    <tabs>SBQQ_Discount_Schedule__c</tabs>
    <tabs>manageid1__c</tabs>
    <tabs>manageidP__c</tabs>
    <tabs>Sowjanya__c</tabs>
    <tabs>Email_validation__c</tabs>
    <tabs>masking__c</tabs>
    <tabs>Sowjanya1__c</tabs>
    <tabs>Sowjanya2__c</tabs>
    <tabs>Sowjanya3__c</tabs>
    <tabs>Sowjanya4__c</tabs>
    <tabs>masktest__c</tabs>
    <tabs>parent__c</tabs>
    <tabs>child__c</tabs>
    <tabs>arjProject__c</tabs>
    <tabs>Cmp_res__c</tabs>
    <tabs>testCustomObjZub__c</tabs>
    <tabs>ArCO1__c</tabs>
    <tabs>ArCo2__c</tabs>
    <tabs>Intern__c</tabs>
    <tabs>Object21__c</tabs>
    <tabs>standard-ProductLimits</tabs>
    <uiType>Lightning</uiType>
</CustomApplication>
