<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Service Console — Keystone org</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>CaseDefault_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Service Agent</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>CaseDefault_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Service Supervisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>CaseDefault_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Case</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <tabs>standard-Case</tabs>
    <tabs>standard-home</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-MessagingSession</tabs>
    <tabs>standard-OmniSupervisor</tabs>
    <tabs>standard-CmsWorkspaces</tabs>
    <tabs>standard-CmsExperiences</tabs>
    <tabs>standard-Macro</tabs>
    <tabs>standard-LightningQuickText</tabs>
    <tabs>standard-Survey</tabs>
    <tabs>vaultp1__c</tabs>
    <tabs>vaultc1__c</tabs>
    <tabs>vaultc2__c</tabs>
    <tabs>vaultc3__c</tabs>
    <tabs>ExternalObject__x</tabs>
    <tabs>Notification__c</tabs>
    <tabs>User_Notification__c</tabs>
    <tabs>CustomObejct1__c</tabs>
    <tabs>CustomObject2__c</tabs>
    <tabs>CustomObject3__c</tabs>
    <tabs>CustObj__c</tabs>
    <tabs>CustObj2__c</tabs>
    <tabs>CustObj3__c</tabs>
    <tabs>testorg__c</tabs>
    <tabs>dlConfig__c</tabs>
    <tabs>CustomAA__c</tabs>
    <tabs>CustomBB__c</tabs>
    <tabs>AshokCustomobj__c</tabs>
    <tabs>AshokLiveTest__c</tabs>
    <tabs>Just_for_testing__c</tabs>
    <tabs>synth__c</tabs>
    <tabs>Testing_for_backup_CI_job__c</tabs>
    <tabs>Thiru_object__c</tabs>
    <tabs>childd1__c</tabs>
    <tabs>manPar1__c</tabs>
    <tabs>manPar10__c</tabs>
    <tabs>manPar11__c</tabs>
    <tabs>manPar12__c</tabs>
    <tabs>vaultA__c</tabs>
    <tabs>vaultB__c</tabs>
    <tabs>vaultC__c</tabs>
    <tabs>vaultD__c</tabs>
    <tabs>vaultE__c</tabs>
    <tabs>vaultF__c</tabs>
    <tabs>vaultG__c</tabs>
    <tabs>vaultH__c</tabs>
    <tabs>vaultJ__c</tabs>
    <tabs>vaultK__c</tabs>
    <tabs>vaultL__c</tabs>
    <tabs>vaultM__c</tabs>
    <tabs>vaultN__c</tabs>
    <tabs>vaultO__c</tabs>
    <tabs>vaultP__c</tabs>
    <tabs>SBQQ_Discount_Schedule__c</tabs>
    <tabs>manageid1__c</tabs>
    <tabs>manageidP__c</tabs>
    <tabs>Sowjanya__c</tabs>
    <tabs>Email_validation__c</tabs>
    <tabs>masking__c</tabs>
    <tabs>Sowjanya1__c</tabs>
    <tabs>Sowjanya2__c</tabs>
    <tabs>Sowjanya3__c</tabs>
    <tabs>Sowjanya4__c</tabs>
    <tabs>masktest__c</tabs>
    <tabs>parent__c</tabs>
    <tabs>child__c</tabs>
    <tabs>arjProject__c</tabs>
    <tabs>Cmp_res__c</tabs>
    <tabs>testCustomObjZub__c</tabs>
    <tabs>ArCO1__c</tabs>
    <tabs>ArCo2__c</tabs>
    <tabs>Intern__c</tabs>
    <tabs>Object21__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>PreconfiguredLightningServiceConsole_UtilityBar</utilityBar>
    <workspaceConfig>
        <mappings>
            <tab>ArCO1__c</tab>
        </mappings>
        <mappings>
            <tab>ArCo2__c</tab>
        </mappings>
        <mappings>
            <tab>AshokCustomobj__c</tab>
        </mappings>
        <mappings>
            <tab>AshokLiveTest__c</tab>
        </mappings>
        <mappings>
            <tab>Cmp_res__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj2__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj3__c</tab>
        </mappings>
        <mappings>
            <tab>CustObj__c</tab>
        </mappings>
        <mappings>
            <tab>CustomAA__c</tab>
        </mappings>
        <mappings>
            <tab>CustomBB__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObejct1__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObject2__c</tab>
        </mappings>
        <mappings>
            <tab>CustomObject3__c</tab>
        </mappings>
        <mappings>
            <tab>Email_validation__c</tab>
        </mappings>
        <mappings>
            <tab>ExternalObject__x</tab>
        </mappings>
        <mappings>
            <tab>Intern__c</tab>
        </mappings>
        <mappings>
            <tab>Just_for_testing__c</tab>
        </mappings>
        <mappings>
            <tab>Notification__c</tab>
        </mappings>
        <mappings>
            <tab>Object21__c</tab>
        </mappings>
        <mappings>
            <tab>SBQQ_Discount_Schedule__c</tab>
        </mappings>
        <mappings>
            <tab>Sowjanya1__c</tab>
        </mappings>
        <mappings>
            <tab>Sowjanya2__c</tab>
        </mappings>
        <mappings>
            <tab>Sowjanya3__c</tab>
        </mappings>
        <mappings>
            <tab>Sowjanya4__c</tab>
        </mappings>
        <mappings>
            <tab>Sowjanya__c</tab>
        </mappings>
        <mappings>
            <tab>Testing_for_backup_CI_job__c</tab>
        </mappings>
        <mappings>
            <tab>Thiru_object__c</tab>
        </mappings>
        <mappings>
            <tab>User_Notification__c</tab>
        </mappings>
        <mappings>
            <tab>arjProject__c</tab>
        </mappings>
        <mappings>
            <tab>child__c</tab>
        </mappings>
        <mappings>
            <tab>childd1__c</tab>
        </mappings>
        <mappings>
            <tab>dlConfig__c</tab>
        </mappings>
        <mappings>
            <tab>manPar10__c</tab>
        </mappings>
        <mappings>
            <tab>manPar11__c</tab>
        </mappings>
        <mappings>
            <tab>manPar12__c</tab>
        </mappings>
        <mappings>
            <tab>manPar1__c</tab>
        </mappings>
        <mappings>
            <tab>manageid1__c</tab>
        </mappings>
        <mappings>
            <tab>manageidP__c</tab>
        </mappings>
        <mappings>
            <tab>masking__c</tab>
        </mappings>
        <mappings>
            <tab>masktest__c</tab>
        </mappings>
        <mappings>
            <tab>parent__c</tab>
        </mappings>
        <mappings>
            <tab>standard-Account</tab>
        </mappings>
        <mappings>
            <tab>standard-Case</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsExperiences</tab>
        </mappings>
        <mappings>
            <tab>standard-CmsWorkspaces</tab>
        </mappings>
        <mappings>
            <tab>standard-Contact</tab>
        </mappings>
        <mappings>
            <tab>standard-LightningQuickText</tab>
        </mappings>
        <mappings>
            <tab>standard-Macro</tab>
        </mappings>
        <mappings>
            <tab>standard-MessagingSession</tab>
        </mappings>
        <mappings>
            <tab>standard-OmniSupervisor</tab>
        </mappings>
        <mappings>
            <tab>standard-Survey</tab>
        </mappings>
        <mappings>
            <tab>standard-home</tab>
        </mappings>
        <mappings>
            <tab>synth__c</tab>
        </mappings>
        <mappings>
            <tab>testCustomObjZub__c</tab>
        </mappings>
        <mappings>
            <tab>testorg__c</tab>
        </mappings>
        <mappings>
            <tab>vaultA__c</tab>
        </mappings>
        <mappings>
            <tab>vaultB__c</tab>
        </mappings>
        <mappings>
            <tab>vaultC__c</tab>
        </mappings>
        <mappings>
            <tab>vaultD__c</tab>
        </mappings>
        <mappings>
            <tab>vaultE__c</tab>
        </mappings>
        <mappings>
            <tab>vaultF__c</tab>
        </mappings>
        <mappings>
            <tab>vaultG__c</tab>
        </mappings>
        <mappings>
            <tab>vaultH__c</tab>
        </mappings>
        <mappings>
            <tab>vaultJ__c</tab>
        </mappings>
        <mappings>
            <tab>vaultK__c</tab>
        </mappings>
        <mappings>
            <tab>vaultL__c</tab>
        </mappings>
        <mappings>
            <tab>vaultM__c</tab>
        </mappings>
        <mappings>
            <tab>vaultN__c</tab>
        </mappings>
        <mappings>
            <tab>vaultO__c</tab>
        </mappings>
        <mappings>
            <tab>vaultP__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc1__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc2__c</tab>
        </mappings>
        <mappings>
            <tab>vaultc3__c</tab>
        </mappings>
        <mappings>
            <tab>vaultp1__c</tab>
        </mappings>
    </workspaceConfig>
</CustomApplication>
