public class A{

Account a1 = new Account();
Account a111 = new Account();
Contact c = new Contact();
Contact c111 = new Contact();
//jhkhugygh
Contact EEE = new Contact();
Contact FFF111 = new Contact();
Contact FFF112 = new Contact();//hbjhuhybhbhvy
//yyuuhhhg
Contact FFF11modi = new Contact();
//CONTACT --FFF11modi = NEW contact();
//hhuggyuhjb
//checkinshamjjjjjjjuly22
//bjvhjvuu
//bhdbdhvd
//d68781
//dhdhggd

}