public Class A100
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai44= new Account();
sai44.Name = name;
return sai44; 
//Modify new trial commnetpavan 98321
// tet sorg98321
///test clas09321
//test claksd090321
//source 000921 source change test final source 090921 source0soruc e9999 444 source001 source001
//source 98 sourc0e osir09ewr0
//source09021
//destination tes871
//check001 pidspao
//autodraft01
//autodraft02
//autodraqft 03 new change
//new change
//test cals901
}        
}