public Class A77
//HelloAR
{
public Account createAccount(String name) //method to create account
{
Account sai44= new Account();
sai44.Name = name;
return sai44; 
//Modify new trial commnetpavan 98321
// tet sorg98321
///test clas09321
//test claksd090321
//source 000921 source change test final source 090921 source0soruc e9999 444 source001 source001
//jkhsai7y871
//test ckas99
//bte661
}        
}